server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    password: root
    username: root
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: update #自动建表
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  freemarker:
    prefix: classpath:static
    suffix: .html
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorized/okta"
            scope: read, write
        provider:
          okta:
            authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize
            token-uri: https://dev-1234.oktapreview.com/oauth2/v1/token
log:
  collect:
    open: true
    file-name: logs/interface-statistics.log
    type: filter
    read-request: true
    urls:
      - /api/*
      - /test/*
